import { type RouteConfig, index, route } from '@react-router/dev/routes';

// Loaders/actions in these route modules are the typed client↔server boundary (no separate API).
export default [
  index('routes/home.tsx'),
  route('oppslag', 'routes/oppslag.tsx'),
  route('orgs', 'routes/orgs.tsx'),
  route('orgs/new', 'routes/orgs.new.tsx'),
  route('orgs/:orgId', 'routes/orgs.$orgId.tsx'),
  route('orgs/:orgId/contacts', 'routes/orgs.$orgId.contacts.tsx'),
  route('orgs/:orgId/contacts/new', 'routes/orgs.$orgId.contacts.new.tsx'),
  route('orgs/:orgId/contacts/:contactId', 'routes/orgs.$orgId.contacts.$contactId.tsx'),
  route('orgs/:orgId/products', 'routes/orgs.$orgId.products.tsx'),
  route('orgs/:orgId/products/new', 'routes/orgs.$orgId.products.new.tsx'),
  route('orgs/:orgId/products/:productId', 'routes/orgs.$orgId.products.$productId.tsx'),
  route('orgs/:orgId/invoices', 'routes/orgs.$orgId.invoices.tsx'),
  route('orgs/:orgId/invoices/new', 'routes/orgs.$orgId.invoices.new.tsx'),
  route('orgs/:orgId/invoices/:invoiceId', 'routes/orgs.$orgId.invoices.$invoiceId.tsx'),
  route('orgs/:orgId/invoices/:invoiceId/pdf', 'routes/orgs.$orgId.invoices.$invoiceId.pdf.tsx'),
  route(
    'orgs/:orgId/invoices/:invoiceId/ehf.xml',
    'routes/orgs.$orgId.invoices.$invoiceId.ehf.tsx',
  ),
  route('orgs/:orgId/bank', 'routes/orgs.$orgId.bank.tsx'),
  route('orgs/:orgId/bank/new', 'routes/orgs.$orgId.bank.new.tsx'),
  route('orgs/:orgId/bank/:accountId', 'routes/orgs.$orgId.bank.$accountId.tsx'),
  route(
    'orgs/:orgId/bank/:accountId/reconcile',
    'routes/orgs.$orgId.bank.$accountId.reconcile.tsx',
  ),
  route('orgs/:orgId/mva', 'routes/orgs.$orgId.mva.tsx'),
  route('orgs/:orgId/mva.xml', 'routes/orgs.$orgId.mva[.xml].tsx'),
  route('orgs/:orgId/reports', 'routes/orgs.$orgId.reports.tsx'),
  route('orgs/:orgId/reports/resultat', 'routes/orgs.$orgId.reports.resultat.tsx'),
  route('orgs/:orgId/reports/balanse', 'routes/orgs.$orgId.reports.balanse.tsx'),
  route('orgs/:orgId/reports/hovedbok', 'routes/orgs.$orgId.reports.hovedbok.tsx'),
  route(
    'orgs/:orgId/reports/hovedbok/:accountId',
    'routes/orgs.$orgId.reports.hovedbok.$accountId.tsx',
  ),
  route('orgs/:orgId/reports/reskontro', 'routes/orgs.$orgId.reports.reskontro.tsx'),
  route('orgs/:orgId/reports/likviditet', 'routes/orgs.$orgId.reports.likviditet.tsx'),
  route('orgs/:orgId/saft', 'routes/orgs.$orgId.saft.tsx'),
  route('orgs/:orgId/saft.xml', 'routes/orgs.$orgId.saft[.xml].tsx'),
  route('orgs/:orgId/vouchers/new', 'routes/orgs.$orgId.vouchers.new.tsx'),
  route('orgs/:orgId/receipts/new', 'routes/orgs.$orgId.receipts.new.tsx'),
  route('auth/login', 'routes/auth.login.tsx'),
  route('auth/callback', 'routes/auth.callback.tsx'),
  route('auth/logout', 'routes/auth.logout.tsx'),
  route('auth/sign-out-everywhere', 'routes/auth.sign-out-everywhere.tsx'),
] satisfies RouteConfig;
