import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import * as schema from './schema.js';

/**
 * Drizzle client. The schema is GENERATED by `pnpm db:introspect` from the SQL migrations —
 * integrity (triggers/RLS/constraints/invoice-counter) lives in db/migrations, not here.
 *
 * Tenancy: set the `app.current_org` GUC per request with `SET LOCAL` so RLS policies apply
 * (defense-in-depth on top of app-layer org filtering). Wire this in the request middleware.
 */
const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error('DATABASE_URL is not set');
}

const client = postgres(connectionString, { prepare: false });

export const db = drizzle(client, { schema });
export type Db = typeof db;
