import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { env } from '../env.js';
import * as schema from './schema.js';

/**
 * Drizzle client. The schema is GENERATED by `pnpm db:introspect` from the SQL migrations —
 * integrity (triggers/RLS/constraints/invoice-counter) lives in db/migrations, not here.
 *
 * `env.DATABASE_URL` is the **app** connection (the non-owner `saldo_app` role in any real
 * environment) so RLS (ADR 0012) applies. Tenancy: set the `app.current_org` GUC per request via
 * `withOrgTx` (SET LOCAL). Auth tables (app_user/user_session/membership) are queried on this plain
 * connection, pre-org, by their secret key (ADR 0020).
 */
const client = postgres(env.DATABASE_URL, { prepare: false });

// The relational query API (`db.query.<table>.findFirst({ with: { … } })`) is unused today, so we keep
// the lighter non-relational client. To enable it, spread the hand-maintained relations alongside the
// tables: `drizzle(client, { schema: { ...schema, ...relations } })` (see `./relations.ts`, whose join
// columns are locked by `test/integrity/relations.integration.test.ts`).
export const db = drizzle(client, { schema });
export type Db = typeof db;
