#!/usr/bin/env bash
# PreToolUse hook (matcher: Edit|Write). Receives the tool-call payload as JSON on stdin.
# Vetoes edits to generated/derived files by exiting non-zero (which surfaces as feedback).
set -euo pipefail

payload="$(cat)"
# Extract the target path from either Edit or Write payloads.
path="$(printf '%s' "$payload" | node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{const j=JSON.parse(s);process.stdout.write(j.tool_input?.file_path||"")}catch{process.stdout.write("")}})')"

case "$path" in
  *"/app/db/schema.ts")
    echo "BLOCKED: app/db/schema.ts is generated by 'pnpm db:introspect'. Edit db/migrations/*.sql instead." >&2
    exit 2
    ;;
  *"/dist/"*|*"/build/"*|*"/.react-router/"*|*"/db/reference/saf-t/"*|*"pnpm-lock.yaml")
    echo "BLOCKED: '$path' is a generated/vendored artifact and must not be hand-edited." >&2
    exit 2
    ;;
esac
exit 0
